### ISSUE TITLE
Attach notification message to a commit

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#105]
The recent addition of a redirect to My Webcourses as part of the user login process requires that Angular be recompiled.

It would be nice if for some _future commit like it_, pulling it generated a message at the console notifying users and giving instructions to recompile Angular. I know messages are possible with pulls or fetches... but not sure if it's per repo, per branch, per commit, or otherwise.

A good starting place might be a search for something like `attach console notification to github commit`. Note that the search results might be git repo specific - watch for other git repo solutions like ones for BitBucket, GitLab... iow, if you're applying a solution you found and it's not working, double check it's not git repo specific. And if you do find a solution that works on e.g. Bitbucket but can't find one for GitHub, you can use it to leverage the answer to find one that works on GitHub. E.g.:

_You find that a message / notification can be generated for BitBucket through adding a -repoMessage flag at commit. If this hypothetical was the solution for BitBucket, you can do a search for "bitbucket repomessage github alternative" or "github equivallent for bitbucket repomessage"_

**Important:** **The solution needs apply for future commits only. There likely is no way to include one on a past commit, nor is it important that we do in this case, since for now we've a small team and the compile is done in installer.sh.**

**Comment by SirL3X0N** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

https://devconnected.com/how-to-git-commit-with-message/

**Comment by bytech-ca** [comment]
https://stackoverflow.com/questions/46081269/is-it-possible-to-attach-a-message-to-a-git-commit-that-will-display-when-pulled

**Comment by bytech-ca** [comment]
This is now setup via GitHub actions (`/.github/workflows/main.yml`). A recompiled is done and checked for errors anytime the master branch is pulled.
