### ISSUE TITLE
Generate and apply a GPG key for signing commits

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#106]
An author of a commit can be forged when commits are not signed with a GPG key.

![Commits-·-eclectic-bytech-webcourses-ngx-v4](https://user-images.githubusercontent.com/33671154/200542280-976a5bb9-2689-4796-832b-f60c8b1fae42.png)

Good starting point might be: https://medium.com/@ryanmillerc/use-gpg-signing-keys-with-git-on-windows-10-github-4acbced49f68

**Comment by SirL3X0N** [comment]
I'm 99% sure i got it but I'm having an error trying to upload to this branch

**Comment by bytech-ca** [comment]
@SirL3X0N Run from the repo directory `git config --list --show-origin` to show all config, and where each is set. The further down the list, the more precedence it has (iow, if a config is set twice, the lower one will apply.)

Since verification is working on your other repo, it's likely you've some local setting in /.git/config (the repo specific config) that is overriding some setting that your other repo doesn't.

**Comment by bytech-ca** [comment]
@SirL3X0N The settings files you've sent me via email suggest, neither your nor the webcourses repository, will get signed.

It could be that you're seeing Verified on your commits, since you added a GPG key to GitHub, and you're the owner of the repo, too.

Try this

1. Edit your `C:/Users/Seth/.gitconfig` file in Visual Studio, remove the miss-typed `user.signinkey ` line.
2. Ensure that you've added to GitHub the key on the previous line, the one beginning with the letter C.
3. Finally, change `commit.gpgsign` to true. This is likely not required for this project, because you've already added that line to the repo's git config. Correcting it here will mean all your future projects will get signed by default.

**Comment by bytech-ca** [comment]
@supcollier 
![Push-Attempt-by-supcollier-·-Pull-Request-107-·-eclectic-bytech-webcourses-ngx-v4](https://user-images.githubusercontent.com/33671154/201637954-fb69d849-5f2b-4e3c-b7ed-f8d0a0534331.png)

**Comment by bytech-ca** [comment]
@supcollier I've sent you a GitHub invite to collier@bytech.ca. Not sure if the email address can be added to your existing collierlee@collierlee.com account, or if a separate one is needed.

**Comment by bytech-ca** [comment]
My key expired, and I followed the instructions for key generation, but kept getting errors after:

```
failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```

Looking at my .gitconfig, I noticed this:

```
[gpg]
	program = C:\\Program Files (x86)\\GnuPG\\bin\\gpg2.exe
```

Once I've re-generated the key using gpg2 instead gpg, my key way accepted. =D
