### ISSUE TITLE
Documentation on Development Breakpoint

### ISSUE THREAD

**Issue by supcollier** [eclectic-bytech/webcourses-ngx-v4#118]
Our documentation on development of WGNX V.4 has a breakpoint for the installation of Vagrant because Vagrant's developers have permanently moved their Vagrant installation and setup pages.

Developers should be able to click the link and install Vagrant without going on a wild goose chase looking for the Vagrant page and instead installing the wrong software or development kit.

The current link redirects to:
https://www.vagrantup.com/vmware/downloads

The new location of vagrant is:
https://developer.hashicorp.com/vagrant/downloads
*You must download the vmware option at the bottom of the page, the other option is not the correct software.

Sincerely,
Collier

![Screenshot_693](https://user-images.githubusercontent.com/80302132/203382779-82d59392-b2e4-4141-9dfd-83312b5d8815.png)
![Screenshot_694](https://user-images.githubusercontent.com/80302132/203382787-ad614533-79dd-49df-a559-07cf5ac12821.png)

**Comment by bytech-ca** [comment]
Thank you, Collier! Link has been updated.
