### ISSUE TITLE
Disable Back button on first activity in course

### ISSUE THREAD

**Issue by SirL3X0N** [eclectic-bytech/webcourses-ngx-v4#130]

**Comment by SirL3X0N** [comment]
Having trouble finding the html file in vs code. (ik i should know this by now)

**Comment by SirL3X0N** [comment]
button is disabled by default when you first load in but when you go back to webcourses and load in again its active

**Comment by bytech-ca** [comment]
In web tools, you'll be able to select the button and see its code. Find something that looks like it might be quite unique, and then `grep` the code (for the front end, best done from `/resources/webcourses/app/src`.) Remember that `grep` will fail on any unescaped, special characters. A search for "escaping special characters when grepping" will give you the syntax info needed...

**Comment by bytech-ca** [comment]
I'm refactoring much of the code around this area - hold off on any work for this issue. I'll likely have this issue fixed along with #147, and if not, the solution to this issue will be very different after #147 is completed.

**Comment by bytech-ca** [comment]
e431d1e9edb36fecd8208170233791e25e7967a0 resolves this issue.
