### ISSUE TITLE
Activity progress bars load dupplicate activity, or don't work at all

### ISSUE THREAD

**Issue by SirL3X0N** [eclectic-bytech/webcourses-ngx-v4#161]

**Comment by SirL3X0N** [comment]
https://user-images.githubusercontent.com/116177078/213691821-1bb7e7cd-0f7a-4712-8979-44de8000c70f.mp4

**Comment by bytech-ca** [comment]
Problem seems to occur only when an activity in the currently loaded set is selected, in both: active and review mode,

**Comment by bytech-ca** [comment]
1195f02f1707fc6d6fa1a59eee6575a78e92b52b resolves this issue
