### ISSUE TITLE
Improve menu consistency between Vue and Angular main menus

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#170]
At http://homestead.test/user/dashboard/ (Vue JS Framework)

- [x] Remove **Dashboard**, add **Home** in its place with a link to `/webcourses` (external linking method)
- [x] Move **My courses** to right side's drop down menu 
- [x] Rename **Course catalogue** to **Webcourses**
- [x] Add **Help** after **Webcourses** (external linking method)
- [x] Comment out **Manage Account** 
- [x] Rename Log out to Sign out

At http://homestead.test/webcourses/user/webcourses (Angular JS Framework)
- [x] Add **Profile** link to right side's menu, just before **Sign out** link (external linking method)

**Comment by SirL3X0N** [comment]
There already is a a profile button in the right hand drop down menu above to sign out link??

**Comment by bytech-ca** [comment]
Ran some tests again today after making sure I've recompiled Vue, reloaded everything properly... this is what I'm seeing as the mobile version of the menu.

![Open-WebCourses](https://user-images.githubusercontent.com/33671154/221557873-ff6f2949-2a78-4b97-bd1a-2e6637f8bcfb.png)

**Comment by SirL3X0N** [comment]
On my last commit on this branch I noticed a bug in which the home button on the shrunk view of the page didn't work so I added a solution for it. however it seems you have deleted the solution but proceeded to merge the branch without another solution. Now on the dashboard when you shrink the screen the home button no longer works

**Comment by bytech-ca** [comment]
Completing the record, the three items in the Vue main menu that need adding are:

- Webcourses (external https://www.cultivatelearning.ca/webcourses/catalogue)
- Publish (external https://publish.cultivatelearning.ca)
- Help (external https://www.cultivatelearning.ca/webcourses/help)

Ideally, like on the Angular side, these will fold into its own menu on the left, with logo in middle, and user menu items separate in a right side menu (as they already are.)

**Comment by SirL3X0N** [comment]
Throwing the links inside of a drop-down menu is a bad idea. All of those links are to front end pages and will require unique redirect links. look at issue: ' Redirect user to My Courses at login #81 ' for an example of this. Whist this is very do able it's long and excessive in my opinion. I suggest we just move the links to a bar below to logo (attached image). This will save time, effort and many messy lines of code. (Imagine items are centered)
![Alternative veiw](https://user-images.githubusercontent.com/116177078/224081953-edca6b05-5984-468b-97d4-f932d2f1514b.png)
