### ISSUE TITLE
wngx_coupons table 'updated_at' field does not get updated when 'uses' is incremented

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#176]
Ideally, this will be resolved with an update to the DB in the form of a column update via a migration. This might be a pure SQL solution, or a Laravel solution:

Both might also work, in which case we want to apply one that is easier, more compatible across database types, or a combo of both considerations.

**Comment by bytech-ca** [comment]
This can probably be best achieved by modifying the `created_at` and `updated_at` fields to have a `CURRENT_TIMESTAMP` default.

Remember to `vagrant ssh` and  `cd code` before running any `php artisan` commands that result in database changes.

**Comment by bytech-ca** [comment]
The "hide course from main catalogue" feature has some extra commentary around tips for Artisan commands.

**Comment by bytech-ca** [comment]
While my idea on modifying the default for the columns in question will probably work for `created_at`, it will not work for `updated_at`. I now suspect that we'll want a Laravel solution, rather than a "on the database level solution" (modifying the default of a column is considered a database level solution.)

We could probably go with a db level solution for created_at and a Laravel level solution for updated_at. However, there will likely be downsides for not going through Laravel for created_at updates... in short, we definitely want to look into finding how Laravel wants us to handle these routines.

**Comment by bytech-ca** [comment]
Mmmmm.... did some quick reading on this. These fields already auto-update, as long as records are added to the database through Laravel. The missing timestamps are a result of adding data on the database level, and not going through Laravel.

This being the case, I suppose we can wrap this issue up by making sure all tables have the created and updated_at fields... I know some do not.

**Comment by SirL3X0N** [comment]
in short scrap everything I'm doing and find a laravel solution to the problem?

**Comment by bytech-ca** [comment]
`created_at` and `updated_at` only get updated when using Eloquent to save records. Using the DB Facade does not update the fields, and its use was in part the problem.
