### ISSUE TITLE
wngx_courses table 'created_on' and "modified_on" field does not get updated or written to

### ISSUE THREAD

**Issue by mrjamiecakes** [eclectic-bytech/webcourses-ngx-v4#179]
When a course is created, the "created_at" table should have a written time there. Instead it is always left empty.

When a course is modified, the "modified_at" table should have a written time there. Instead it is always left empty.

This issue seems to be related to a Laurvel switch that can be resolved with 1 line of code or 2. This is especially important to fix as to resolve customer technical troubleshooting and to ensure realtime integrity and security.

This issue should be resolved with a switch and/or a CDCI file in the migrations to wngx_courses.

**Comment by mrjamiecakes** [comment]
This issue will have an attached completition payout bounty of $20 or $50. (Pending)

**Comment by mrjamiecakes** [comment]
This issue is caused because some courses being manually hand entered. They way we want to fix this issue is acutely impossible.

This isn't an issue anymore, rather a small bug that doesn't need to be a marked issue. This only occurs when data is manually entered into the database and not thru Laravel. It is working as intended.

**Comment by bytech-ca** [comment]
`created_at` and `updated_at` only get updated when using Eloquent to save records. Using the DB Facade does not update the fields, and its use was in part the problem.
