### ISSUE TITLE
Url parameters need to be passed after login and new registration redirect

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#185]
When a URL parameter is added to the registration / login address e.g. https://v4.cultivatelearning.ca/user/register?code=abc` (note the `?code=abc`), it does not survive the redirect after reg/login.

Places to look:
- grep for HOME from root project directory - that file might contain an option to axe or keep the parameter
- search for `laravel 9 retain url parameters on forward after login` or similar.

Dealing with a second wave of the flu, might be slow to respond - passive communication, when possible, is appreciated 🤪

**Comment by bytech-ca** [comment]
Well, I had a crack at this one yesterday for about three hours, and didn't solve it. Our method of redirecting out of Laravel and into Angular pretty much ensures all URL parameters get wiped in the process. This'll likely mean we can't rely on built in method.

**Comment by SirL3X0N** [comment]
so where do we go from here?
