### ISSUE TITLE
Expand wngx_users to include and populate last_login_time and last_login_ip

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#189]
Great 5 minute video for this task can be found at https://www.youtube.com/watch?v=v4IRYiylQPs
We're using Laravel Jetstream, though the solution in the above video is quite universal.

- [x] Migration to add last_login_time (timestamp) and last_login_ip (string(15))
- [x] Update User Model (`app/Models/User.php`) to make last_login_time and last_login_ip fillable
- [x] Add Login listener to populate the fields at login
- [x] Test whether login populates the fields
- [x] Make note in this issue, on whether this event is also triggered with new user registrations

**Comment by SirL3X0N** [comment]
https://youtube.com/clip/Ugkxxr28zi1RuXedQbVvlOJzacSSZgOJEfTB missing file is causing confusion

**Comment by bytech-ca** [comment]
File is at `\vendor\laravel\framework\src\Illuminate\Auth\Events\Login.php`.
He's referencing it only to show which properties are available to `$event` in `handle($event)` (timestamp 2:55). No changes are needed to that file.

Nothing in the vendor directory should ever be modified. These files are over-written each time a new install is done, or when an update on packages is made. Anytime you see a tutorial that references files inside `/vendor` (for PHP libraries) and `/node_modules` (for JS libraries), it's probably to give you insight on sources of data used in the next step.

**Comment by bytech-ca** [comment]
Awesome job @SirL3X0N ! The only change I made that's worth mentioning is to move the two new columns to come before created_at and updated_at - these seem to always come last by default, and I wanted to keep with that convention.

Squash merge e267ccbd0637873e7d044efe019015c140ba2ef6 resolves this issue.
