### ISSUE TITLE
Prevent Google FLoC IDs

### ISSUE THREAD

**Issue by webcourse-ng** [eclectic-bytech/webcourses-ngx-v4#2]
Set header  `Permissions-Policy: interest-cohort=()` to prevent Google user tracking sans-cookies. See DuckDuckGo's https://spreadprivacy.com/block-floc-with-duckduckgo/ on what it is.

**Comment by bytech-ca** [comment]
3cf77d3e7506b94d143f14abe188cbb87ce3ef44 resolves the issue
