### ISSUE TITLE
Update user dashboard right hand dropdown menu to show role specific options

### ISSUE THREAD

**Issue by SirL3X0N** [eclectic-bytech/webcourses-ngx-v4#212]

**Comment by bytech-ca** [comment]
@SirL3X0N We want the options in the right hand, user menu, which is what I assume you meant. :D

You've now admin and publisher access, and will be able to see what those options look like and where they link.

Please update your password to one generated by Bitwarden, and see if you can get TFA enabled - it seems to be working on and off. I recommend Authy for TFA as it has web access, in case you've no access to your mobile.

**Comment by bytech-ca** [comment]
@SirL3X0N About CSFR, in web dev console only, or something extra that you're getting?

**Comment by bytech-ca** [comment]
@SirL3X0N Some clarification and corrections to what I said on the phone earlier today:

- `/user/profile` from Inertia/Vue include `owned_teams` and `all_teams`.
- `/v4/user/profile` does not include  these properties.

Best solution might be to find a way to replace the call to `/v4/user/profile` with call to `/user/profile`, and get rid of the `/v4/user/profile` route in `web.php`. It might be as simple as changing the call address in Angular's user service, and updating the User model in Angular to reflect the new user object structure.
