### ISSUE TITLE
Add favicon to Vue sections

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#220]
Angular pages show a favicon, Vue doesn't. It'll have to be added to Vue source, so it gets copied when it's recompiled (i.e. `/public` is deleted and recreated each time a recompile is done.)

**Comment by SirL3X0N** [comment]
I'm a little lost here can you clarify exactly what you mean? *preferably in English*

**Comment by SirL3X0N** [comment]
@bytech-ca  just reminding you to look at this branch as you said not to make a pull request
