### ISSUE TITLE
Hide course from main catalogue

### ISSUE THREAD

**Issue by webcourse-ng** [eclectic-bytech/webcourses-ngx-v4#24]
This is achieved in v2 by adding conditionals to API sql that filter out private courses. This allows for showing the courses in the publisher's catalogue, but not the main one.

In v4 we probably want to add to _courses table "options", with something like a "hide_from_main_catalogue" property.

**Comment by bytech-ca** [comment]
Created a branch for this issue.

**Comment by bytech-ca** [comment]
If we need to make change to the table, we'll need a new migration file. Best way to get started on that is to run `php artisan make:migration update_courses_table` at command line (you'll probably have to be in the root of the project for the `artisan` command to be found.

**Comment by bytech-ca** [comment]
Modify `app\Http\Controllers\CourseController.php` to check if course should be fetched.
