### ISSUE TITLE
Switch to Eloquent in CourseEditorController

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#259]
This one has a double implementation of DB::Facade. The first should now look familiar.

The second (`update(['demo' => DB::raw('NOT demo')])`) flips the value of the `demo` field: if it's a 1, it changes it to 0, and vice versa. In other words it sets demo to what it isn't... NOT `demo`. A search for something along the lines of _how to flip binary value using Eloquent_ will probably be needed.

ChatGPT is also good at this sort of thing. Telling it "I have a course_syllabus laravel table. I need to flip the binary field "demo". How do I do that using Eloquent?" might give you the exact code for coping and pasting.

To help with testing, break this task into two.

1. Update DB::table to Eloquent to always save a 1 to the field
2. When first step is tested and working, start tweaking the code to flip values, instead always saving a 1.

**Comment by SirL3X0N** [comment]
Is there any reason in particular demo isn't a boolean?
