### ISSUE TITLE
Implement MonoLog for Slack notifications (sign-up and course join)

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#282]
Laravel includes [MonoLog](https://packagist.org/packages/monolog/monolog), a logging application. We probably want to replace our custom code with MonoLog... and then see if we can expand to also sending Telegram notifications using the same method.

**Comment by SirL3X0N** [comment]
https://laravel.com/docs/10.x/logging

In the introduction it says laravel uses monolog when using the notification channels. ie we are already using it
