### ISSUE TITLE
Catalogue pages need be updated to use EnterCourseModule

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#306]
Code for the `Enter` course button has been modularised at `\resources\webcourses\src\app\pages\components\buttons\enter-course`.

- [x] Catalogue pages need be updated to use it, instead its own embedded logic.
- [x] Button label should be "review" when course is completed, "resume" when partially completed, and "begin" when not yet started
- [x] Rename the module from `EnterCourseModule` to `EnterCourseButtonModule`

**Comment by SirL3X0N** [comment]
You couldn't have put the rename as the first item on the list : (
