### ISSUE TITLE
Turn into component "Showing records y to x of z" code

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#307]
First, let's tripple check that there is no function akin to `ngb-pagination` for generating this feature.
If not, let's make it into its own module at `src\app\components\pagination\showing`

**Comment by bytech-ca** [comment]
Had a bit of a look into this, and we definitely will want to modularise this option. The question "how" is what's left to answer.

Found a [two part blog post with a tutorial](https://medium.com/@nmpiash/laravel-angular-material-server-side-pagination-part-1-3c95f981ae45). Initial post is for Angular 5, so take code syntax with a huge grain of salt. The follow-up is for NG11 (?), so getting more current.

**Comment by bytech-ca** [comment]
I've created a new branch with "showing records" designed in a way that can be templated.

Essentially, we were recreating pagination on our own, and that made it very difficult to modularise. We're now using `ngb-pagination` just like at the bottom of the page. Then, we're templating it using `<ng-template ngbPaginationPages>`. The ngb-pagination authors let anyone write their own template, if none of the default template settings get the desired results.

I've commented out the original "showing records" code to clearly show what we're doing different. It should be removed before creating a pull request.

**Comment by SirL3X0N** [comment]
I have completed this issue and was cleaning up branches after working all night and deleted the branch by accident. I've lost all my work. I'm working on a new branch from scratch

**Comment by bytech-ca** [comment]
Merged into master before noticing that the names  of the modules are too generic. Let's rename and move it to `src\app\components\pagination\showing` (originally suggested in the Dec 15th comment above.) Other than that, no issues. :D

**Comment by bytech-ca** [comment]
Merged into master
