### ISSUE TITLE
Production installer should ask user for database connection details

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#309]
Production installer is now in `install.sh`. It fails when it gets to running database commands, since there is no database to run these on.

There are many hurdles to creating the database automatically, but we can fix this item through prompts for:

- database name
- user name
- password

`install.sh` should ask for these, and then update the .env file with details provided by user. For extra help, see cfa40cad43470dd51aaabc556adb5c401cb1246f commit for comments right inside of `install.sh`.

Search for or ask ChatGPT about ***interactive shell scripts with user input*** and ***write to file / update values from shell script*** for help getting started.

This task will be considered completed when running `install.sh` asks for data listed above, and updates the .env with user entered details.

**Comment by mrshychip** [comment]
> [!IMPORTANT]
> This issue is complete. There are technical issues that need to be resolved before I am able to push my changes to the branch.
