### ISSUE TITLE
Remove hardcoded path from Copy Access code

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#314]
`src\app\admin\publisher\discount-codes\discount-codes.component.html` has **cultivatelearning.ca** hard coded. It should instead use the `domain` property from `public\webcourses\config.json`.

**Comment by mrshychip** [comment]
> [!IMPORTANT]
> I do not think I will be able to complete this milestone within then time I have been provided, given my damaged equipment and delicate setup. Additional time may be required to complete this milestone.

**Comment by mrshychip** [comment]
> [!NOTE]
> I see that @SirL3X0N has taken over this issue. I am no longer working on this issue and as such I have removed myself from the issue entirely.
