### ISSUE TITLE
POST end-point to save user answers

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#34]
__Path:__ `/webcourse/activities/{aid}/user_answer`  

Save user answers. There are:

__Binary answers__
Every activity - including Info type activities - generate an entry in the binary answers table. Depending on case, we store either the answer_id's that the user selected, or the ID of a...

__Long answer__
Saved as varchar, long answers contain text - for some activity types as JSON

**Comment by webcourse-ng** [comment]
Binary answers are now being saved - one per activity, and extra steps are needed to save multiple answers (like checkbox multi-answers.) Separate issues should be created for next sprint and various activity types for the finish.
