### ISSUE TITLE
Create Fake API

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#36]
Tweak dev environment to allow development without running `npm run-script build:prod` in order to test a change. Normally this means accessing the website via localhost:4200.

**Potential solution: ** localhost could use a fake api that returns expected model objects

**Comment by bytech-ca** [comment]
This looks like a good solution for a fake API:
https://firstclassjs.com/mock-fake-backend-api-in-angular-how-to/

**Comment by webcourse-ng** [comment]
Perhaps this is where we should be using Laravel's Faker to create dummy data and allow the API to run and be accessed like a real app...

**Comment by bytech-ca** [comment]
Resolved with #65
