### ISSUE TITLE
Add Demo Course to repo

### ISSUE THREAD

**Issue by webcourse-ng** [eclectic-bytech/webcourses-ngx-v4#44]
The platform should come with the CL demo course.
Let's make it happen, team!

**Comment by webcourse-ng** [comment]
SQL imports for Demo Course pulled from cultivatelearning.ca course copy: [demo-course-sql.txt](https://github.com/eclectic-bytech/webcourses-ngx-v4/files/7921442/demo-course-sql.txt)

**Comment by webcourse-ng** [comment]
Here is the course again with a few important updates:  
[demo-course.sql.txt](https://github.com/eclectic-bytech/webcourses-ngx-v4/files/8476300/demo-course.sql.txt)

**Comment by webcourse-ng** [comment]
I attached a branch to this issue - please use it instead creating your own.  
It'll help with integrating pull requests.

**Comment by iamcollierlee** [comment]
```diff
+In Progress
```

**Comment by iamcollierlee** [comment]
```fix
Using demo-course.sql.text as source in demo-course.sql.
```

**Comment by iamcollierlee** [comment]
Creating a DemoCourseSeeder with 59 database seeds.

Estimated completion time: 1-2 hours.

**Comment by iamcollierlee** [comment]
```diff
+Finished writing 59 database seeds.
```
```diff
+Finished writing properties to database seeds.
```

Writing seed data to seeds.

**Comment by webcourse-ng** [comment]
The code is looking good, but code is a bit like mushrooms in the forest: it's not just how it looks, but the environment where you're finding it. So, the code is looking good... and before I can properly review it, please add it to a repo where I can see it run as well. 

If the file is not part of the repo, then it's probably too early for a code review. :)

**Inside the Issue Tracker:** here is a good place to post a method you're thinking or working on implementing. Like the course seeder idea.

This is where anyone working on the code can chime in. You might get feedback like "I already tried that way, and moved on because..." or, "hey, if you're thinking of rewriting sql for laravel import, I know a tool!" (Incidentally, I think there was a SQL to Seeder converted in earlier versions of Laravel, but it looks like it might have been too time consuming to maintain.)

**Comment by iamcollierlee** [comment]
I will be making a pull request with the DemoCourse file. I didn't add it to the installer because @webcourse-ng will be reviewing an issue getting multiple data in our PHP remake of the SQL for Seeder.

We might want to look at getting the seeder to read .sql files or looking at a converter to create PHP files from sql.
