### ISSUE TITLE
Add a pre-existing admin account

### ISSUE THREAD

**Issue by webcourse-ng** [eclectic-bytech/webcourses-ngx-v4#45]
On a fresh install, there should be a default admin account already created without need to register.  
Include the default credentials in the main readme.

**Comment by webcourse-ng** [comment]
Let's achieve this using Laravel Seeder, or first discuss other approaches that might be valid for our setup.
Use:

User: openwngx
Pass: password

**Comment by iamcollierlee** [comment]
To disable teams we require to overhaul a decent chunk of the core structural code. This makes teams optional and has the system handle people without a team obtain a trait of "HasNoTeam" to prevent a breakpoint of the core system.

I have found verified steps on how to do this here:
https://npratley.net/disabling-personal-teams-in-laravel-8-and-jetstream-1fd083593e08/

**Comment by iamcollierlee** [comment]
```diff
+I have resolved this issue and added a default account with a default team.
+
+Pending resolved by admin.
```
