### ISSUE TITLE
Jetstream's Dashboard link doesn't work

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#60]
Recreating the problem:

1. [Sign in](https://homestead.test/user/login) to the platform using an anon browser window (user: example@example.com, pass: password)
2. Navigate to http://homestead.test via browser's url input
3. Click **_Dashboard_** in top right corner

The sequence ends at a Laravel 404 page.

Let's solve this one by rerouting `/dashboard` to `/user/dashboard` inside `/routes/web.php`, and adding the following comment to the code:

`Added after moving /dashboard to /user/dashboard to fix issue #60`

**Comment by mrshychip** [comment]
🔎 This is a recently known bug by the Jetstream developers. I am working on a workaround while the developers fix their bug.

**Comment by mrshychip** [comment]
This problem is linked to user's creation, either from a factory or directly with User::create : neither creates a personal_team, which seems to be required when using Jetstream.

![Screenshot_266](https://user-images.githubusercontent.com/80302132/186215803-e1709981-8d8e-4661-8a3b-d3566961d8ab.png)

**Comment by mrshychip** [comment]
This issue is pending closed. A pull request with a new branch was completed.

Added:
A Personal Team Flag - Mandatory for Jetstream

**Comment by bytech-ca** [comment]
Unable to test the code due to the branch having been created from the broken issue #57 commits :( I think I now got the master cleaned up, and will cherry-pick this commit to see if it works.

**Comment by bytech-ca** [comment]
> 🔎 This is a recently known bug by the Jetstream developers. I am working on a workaround while the developers fix their bug.

I can't find this being a documented bug - a link would be much appreciated as it can help the team in resolving it in a way that benefits the whole community.

**Comment by bytech-ca** [comment]
For now, let's solve this one by rerouting `/dashboard` to `/user/dashboard` inside `/routes/web.php`, and adding the following comment to the code:

`Added after moving /dashboard to /user/dashboard to fix issue #60`

**Comment by bytech-ca** [comment]
Issued fixed in 3afb50faaff248260d1f87d4980cc4eaf935bd7f
