### ISSUE TITLE
Update init.sh with reminder to add homestead.test and localhost to local hosts/DNS

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#79]
After the installation of WNGX, a message with an eye popping, **colourful reminder**, to add homstead.test to the local DNS or hosts file will be helpful. It should be added at the end of root's `init.sh` file.

Proposed content:

> Remember to add to your hosts/DNS config :  
> - homestead.test 192.168.52.52
> - localhost 127.0.0.1 (required when running `npm run api`)

Please use the already created `79-dns-update-reminder` branch for this task and submit pull request upon completion.

**Comment by mrshychip** [comment]
A resolution to this issue is in progress. I plan to have this completed today.

**Comment by bytech-ca** [comment]
7b1b0256cb9d0dbacbdb22bd054a86aeae710165 completes this task,
